version: "3.9"

services:
  client:
    container_name: client
    build: ./frontend
    volumes:
      - build_client:/var/www/html
    depends_on:
      - app

  app:
    container_name: app
    build: ./node
    ports:
      - 5000:5000
    depends_on:
      - plantshop_db 
    env_file:
      - ./node/.env.development
    volumes: 
      - ./node:/app
      - node_modules:/app/node_modules

  plantshop_db:
    image: postgres
    container_name: plantshop_db
    restart: always
    ports:
      - 2345:5432
    env_file:
      - ./node/.env.development
    volumes: 
      - postgres:/var/lib/postgresql/data
  
  nginx:
    build: ./nginx
    container_name: nginx
    restart: always
    ports:
      - 80:80
    volumes:
      - build_client:/var/www/html
    depends_on:
      - client
      - app

volumes:
  node_modules:
  build_client:
  postgres: