version: "3.9"

services:
  client:
    container_name: client
    restart: always
    build: ./frontend
    ports:
      - 3000:3000
    depends_on: 
      - app
    volumes:
      - build_client:/var/www/html

  app:
    container_name: app
    restart: always
    build: ./node
    ports:
      - 5000:4000
    depends_on:
      - plantshop_db 
    env_file:
      - .env.development
    volumes: 
      - .:/apps

  plantshop_db:
    image: postgres
    container_name: plantshop_db
    restart: always
    ports:
      - 2345:5432
    env_file:
      - .env.development
    volumes: 
      - postgres:/var/lib/postgresql/data
  
  nginx:
    build: ./nginx
    container_name: nginx
    ports:
      - 80:80
    volumes:
      - build_react:/var/www/html
    depends_on:
      - client

volumes:
  client:
  postgres: